---
title: "Exception Handling"
sidebar_label: "Exception Handling"
sidebar_position: 10
description: "Understanding exceptions in Java: types, handling, and best practices."
tags: ["Key Concepts", "Java", "Exceptions"]
---

# Exception Handling

## What Is an Exception

An exception is an event, which occurs during the execution of a program, that disrupts the normal flow of the program's instructions.

When an error occurs within a method, the method creates an object and hands it off to the runtime system. The object, called an exception object, contains information about the error, including its type and the state of the program when the error occurred. Creating an exception object and handing it to the runtime system is called **throwing an exception**.  
[See Oracle Docs for details](http://docs.oracle.com/javase/tutorial/essential/exceptions/index.html)

For example:
- A user might type an invalid filename
- An accessed file does not exist or might contain corrupted data
- A network link could fail
- ...

Circumstances of this type are called exception conditions in Java and are represented using objects (all exceptions descend from `java.lang.Throwable`).

Consider the code that causes an exception:

![Exception code example](/media/exception.webp)

At line 4, the `main` method causes an error and creates an exception object of type `ArithmeticException`. The JVM throws it to the `main` method. Because `main` does nothing to control this error, the output looks like this. When the error occurs at line 4, the statement at line 5 is skipped.

## Kinds of Exception

### Checked exception

Checked exceptions are checked at compile time. You must handle them by either the try-catch mechanism or the throws-declaration mechanism.

*For example:*

![Checked exception example](/media/exception2.webp)

In the above example, the method `FileReader()` is throwing an exception. You must use try-catch or throws to handle it.

### Unchecked exception

An unchecked exception occurs at runtime. These are also called Runtime Exceptions. The program wonâ€™t give a compilation error. Most of the time, these exceptions occur due to bad data provided by the user during interaction.

*For example:*

![Unchecked exception example](/media/exception1.webp)

If you declare an array of size 5 and try to access the 6th element, an error occurs.

[See more details](https://stackify.com/types-of-exceptions-java/)

## How to fix

We can use try-catch or throws mechanisms to handle and avoid these errors.

### try-catch mechanism

Consider the flow and syntax:

![Try-catch syntax](/media/exception3.webp)

The `try` statement allows you to define a block of code to be tested for errors while it is being executed.

The `catch` statement allows you to define a block of code to be executed if an error occurs in the try block.

The `finally` statement lets you execute code after try...catch, regardless of the result.

:::note
You cannot use `finally` without a `try` block. The `finally` block is optional.
:::

In the example **DemoException2**, we will edit:

![DemoException2 example](/media/exception5.webp)

When the program runs to line 14, if the file name "computer.txt" does not exist, an exception object of type `FileNotFoundException` is created by `main` and thrown to the catch block. The variable `e` stores the address of the object. In the catch block, you can use `e` to get error information.

**The Output will be:**

```
something are wrong
try-catch is finished
```

In the example **ExceptionDemo_1**, we will edit:

![ExceptionDemo_1 example](/media/exception4.webp)

When you try to get the 6th element, an exception object of type `ArrayIndexOutOfBoundsException` is created. The JVM throws the object to the catch block.

**The output will be:**

```
1,2,3,4,5,something are wrong
try-catch is finished
```

### throws mechanism

In the example **DemoException2**, the error occurs in `main`. To fix a checked exception, we use the `throws` keyword. We will edit:

![throws mechanism example](/media/exception6.webp)

**The output will be:** something are wrong if the file name "computer.txt" does not exist.

## Examples

The code below prints out "age is 20 or older" if age is below 20 or if you input text:

![Age example code](/media/exception7.webp)

When the code runs to line 20, if you input text "hello", an exception object is created and thrown to the catch block. The output will be:

![Output for hello input](/media/exception8.webp)

If you input 18, the statement `throw new Exception()` creates an exception object, which is thrown to the catch block. The output will be:

![Output for 18 input](/media/exception9.webp)

## Summary

- A try block is always followed by a catch block, which handles the exception that occurs in the associated try block.
- A single try block can have multiple catch blocks. See [catching multiple exceptions in Java](https://docs.oracle.com/javase/7/docs/technotes/guides/language/catch-multiple.html).
- A try statement may be nested inside either the try or catch block of another try statement. See [Nesting of try/catch Blocks](https://beginnersbook.com/2013/04/nested-try-catch/#:~:text=When%20a%20try%20catch%20block,that%20that%20catch%20block%20executes.).
- When you write a method that causes an exception, if you do not want to handle this error you can throw it to another method using the `throws` keyword.
- You can create your own exception classes. See [Custom Exception Classes](https://www.javatpoint.com/custom-exception).

## Course slide

- [Exceptions.pdf](/media/Exception%20Handling.pdf)

## Workshop

- Complete the [workshop2](/media/workshop2.pdf)
